- name: add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: component != "web"

- name: Create a app directory if it does not exist for roboshop
  ansible.builtin.file:
    path: /app
    state: directory
  when: component != "web"

- name: "Download {{component}} application source code zip file"
  ansible.builtin.get_url:
    url: "http://34.234.65.6:8081/repository/{{component}}/com/roboshop/{{component}}/{{version}}/{{component}}-{{version}}.zip"
    dest: /tmp

- name: "Extract {{component}}.zip to /app directory"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{version}}.zip"
    dest: /app
    remote_src: yes
  when: component != "web"

- name: "extract web.zip file in /usr/share/nginx/html directory"
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  when: component == "web"