- name: install npm dependencies
  ansible.builtin.command: npm install 
  args:
    chdir: /app
  when: component != "shipping"

- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app
  when: component == "shipping"