- name: Install maven
  ansible.builtin.package:
    name: maven
    state: present

- ansible.builtin.import_role:
    name: common
    tasks_from: downloadSourceCode

- ansible.builtin.import_role:
    name: common
    tasks_from: installDependencies
  
- name: move artifact to app directory
  ansible.builtin.command: mv /app/target/shipping-1.0.jar /app/shipping.jar
  
- ansible.builtin.import_role:
    name: common
    tasks_from: loadDataToMySQL

- ansible.builtin.import_role:
    name: common
    tasks_from: startService
  notify:
    - started-service

# - name: new deployment
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: deployment
#   tags:
#     - deployment